name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 3.0.0
homepage: https://win32.pub
repository: https://github.com/dart-windows/winmd
issue_tracker: https://github.com/dart-windows/winmd/issues
publish_to: none # remove when we switch live

topics:
  - winmd
  - windows
  - metadata

environment:
  sdk: '>=3.0.0 <4.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32:
    git:
      url: https://github.com/dart-windows/win32.git
      ref: winmd3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  checks: ^0.2.2