name: winmd
description: A Dart package for working with Windows Metadata (WinMD) formats.
version: 4.0.0
homepage: https://win32.pub
repository: https://github.com/dart-windows/winmd
issue_tracker: https://github.com/dart-windows/winmd/issues

topics:
  - winmd
  - windows
  - metadata

environment:
  sdk: '^3.1.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  archive: ^3.3.9
  ffi: ^2.1.0
  nuget: ^0.1.0
  win32: ^5.0.7
  win32_registry: ^1.1.1

dev_dependencies:
  checks: ^0.2.2
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
