name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 3.0.0
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  archive: ^3.3.6
  ffi: ^2.0.1
  http: ^0.13.5
  win32: ^4.1.1
  win32_registry: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  checks: ^0.2.1
