name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 2.4.0
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  win32: ^3.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7
