name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 2.2.5
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  win32: '>=2.7.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
