name: winmd
description: A Dart library for working with Windows Metadata (winmd) formats.
version: 1.0.23
repository: https://github.com/timsneath/winmd
issue_tracker: https://github.com/timsneath/winmd/issues

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ffi: ^1.1.2
  win32: '>=2.3.3 <4.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1